### ISSUE TITLE
How to do multiple teleport location?

### ISSUE THREAD

**Issue by carlchandev** [Siyuanw/kinesis#24]
When opening the webpage for the first time, I can do a teleport once. After that, clicking the map only allow me to navigate with walk/ride/drive, but it doesn't let me teleport again.

How to do multiple teleport location?

I would like to click on the map and hit teleport anytime I want.

**Comment by carlchandev** [comment]
I just figured it out myselft. Holding a position a few seconds and release to teleport.
(it doesn't always work though)

**Comment by Siyuanw** [comment]
@carlchandev the app is designed to avoid unexpected teleportation. After your first teleportation, you can **drag** the marker to a new place, and there will be a confirmation before it teleports.
