### ISSUE TITLE
Connect an iPhone in WiFi network

### ISSUE THREAD

**Issue by terryyuen** [Siyuanw/kinesis#25]
Is it possible to set fake location for an iPhone within the same WiFi network? 
pymobiledevice3 supports this feature. 
Thank you for your help.

**Comment by Siyuanw** [comment]
@terryyuen unfortunately, the RemoteXPC only supports wired connection. And this project focuses on iOS 17 only.
https://github.com/doronz88/pymobiledevice3#working-with-developer-tools-ios--170
