### ISSUE TITLE
Is this for Mac users only?

### ISSUE THREAD

**Issue by FedoB** [Siyuanw/kinesis#4]

**Comment by Han-Zhao** [comment]
I made it work on Mac. It should work on Linux but won't work on Windows straight away.
I tried it in WSL I had no luck. I sucessfully ported my device USB connection into WSL via https://learn.microsoft.com/en-us/windows/wsl/connect-usb but pymobiledevice3 still couldn't find the device

**Comment by FedoB** [comment]
I tried on Linux but I’m getting the same problem with pymobiledevice3. Reading the repo it seems like only Mac is supported for ios17+
