### ISSUE TITLE
Failed building wheel for uvloop during install

### ISSUE THREAD

**Issue by JyloPen** [Siyuanw/kinesis#8]
Hello! when running `pip3 install -r requirements.txt` I had the attached output. Is there something I'm doing wrong?
<img width="848" alt="Screen Shot 2023-10-08 at 11 28 31 AM" src="https://github.com/Siyuanw/kinesis/assets/147313229/a9a88529-05d9-43d9-b432-58b25d9766fa">

**Comment by leehaipei** [comment]
> Hello! when running `pip3 install -r requirements.txt` I had the attached output. Is there something I'm doing wrong? <img alt="Screen Shot 2023-10-08 at 11 28 31 AM" width="848" src="https://user-images.githubusercontent.com/147313229/273458545-a9a88529-05d9-43d9-b432-58b25d9766fa.png">

What is your Python version? I encountered the same error when using a higher version of Python. When I downgraded Python to 3.8.4, everything was fine.

**Comment by Han-Zhao** [comment]
Don't use python 3.12. 3.11.6 works fine @JyloPen

**Comment by JyloPen** [comment]
Downgrading worked perfectly, thank you!

**Comment by Dkla** [comment]
Thank you!   Be sure to uninstall 3.12 (if you already have it installed) before using 3.11.6.   Enjoy!! :)
